In [62]:
import pandas as pd
import numpy as np

df=pd.read_csv(r'C:\Users\Administrateur\Documents\MEGA\IT Quant\Python\Data\vgsales.csv')
df

,Rank,Name,Platform,Year,Genre,Publisher,NA_Sales,EU_Sales,JP_Sales,Other_Sales,Global_Sales
0,1,Wii Sports,Wii,2006.0,Sports,Nintendo,41.49,29.02,3.77,8.46,82.74
1,2,Super Mario Bros.,NES,1985.0,Platform,Nintendo,29.08,3.58,6.81,0.77,40.24
2,3,Mario Kart Wii,Wii,2008.0,Racing,Nintendo,15.85,12.88,3.79,3.31,35.82
3,4,Wii Sports Resort,Wii,2009.0,Sports,Nintendo,15.75,11.01,3.28,2.96,33.00
4,5,Pokemon Red/Pokemon Blue,GB,1996.0,Role-Playing,Nintendo,11.27,8.89,10.22,1.00,31.37
...,...,...,...,...,...,...,...,...,...,...,...
16593,16596,Woody Woodpecker in Crazy Castle 5,GBA,2002.0,Platform,Kemco,0.01,0.00,0.00,0.00,0.01
16594,16597,Men in Black II: Alien Escape,GC,2003.0,Shooter,Infogrames,0.01,0.00,0.00,0.00,0.01
16595,16598,SCORE International Baja 1000: The Official Game,PS2,2008.0,Racing,Activision,0.00,0.00,0.00,0.00,0.01
16596,16599,Know How 2,DS,2010.0,Puzzle,7G//AMES,0.00,0.01,0.00,0.00,0.01
16597,16600,Spirits & Spells,GBA,2003.0,Platform,Wanadoo,0.01,0.00,0.00,0.00,0.01

In [63]:
df.describe()

,Rank,Year,NA_Sales,EU_Sales,JP_Sales,Other_Sales,Global_Sales
count,16598.000000,16327.000000,16598.000000,16598.000000,16598.000000,16598.000000,16598.000000
mean,8300.605254,2006.406443,0.264667,0.146652,0.077782,0.048063,0.537441
std,4791.853933,5.828981,0.816683,0.505351,0.309291,0.188588,1.555028
min,1.000000,1980.000000,0.000000,0.000000,0.000000,0.000000,0.010000
25%,4151.250000,2003.000000,0.000000,0.000000,0.000000,0.000000,0.060000
50%,8300.500000,2007.000000,0.080000,0.020000,0.000000,0.010000,0.170000
75%,12449.750000,2010.000000,0.240000,0.110000,0.040000,0.040000,0.470000
max,16600.000000,2020.000000,41.490000,29.020000,10.220000,10.570000,82.740000

In [64]:
df.values

array([[1, 'Wii Sports', 'Wii', ..., 3.77, 8.46, 82.74],
       [2, 'Super Mario Bros.', 'NES', ..., 6.81, 0.77, 40.24],
       [3, 'Mario Kart Wii', 'Wii', ..., 3.79, 3.31, 35.82],
       ...,
       [16598, 'SCORE International Baja 1000: The Official Game', 'PS2',
        ..., 0.0, 0.0, 0.01],
       [16599, 'Know How 2', 'DS', ..., 0.0, 0.0, 0.01],
       [16600, 'Spirits & Spells', 'GBA', ..., 0.0, 0.0, 0.01]],
      dtype=object)

In [65]:
import pandas as pd
from sklearn.tree import DecisionTreeClassifier

ms= pd.read_csv(r'C:\Users\Administrateur\Documents\MEGA\IT Quant\Python\Data\music.csv',';')
X=ms.drop(columns=['genre'])

y=ms['genre']

model=DecisionTreeClassifier()
model.fit(X,y)

ModuleNotFoundError: No module named 'sklearn'

In [ ]:
ms.describe()

In [ ]:
y=ms['genre']
y

from sklearn.tree import DecisionTreeClassifier
model=DecisionTreeClassifier()
model.fit(x,y)

In [ ]:

import numpy as np
import matplotlib.pyplot as plt

plt.plot([1, 2, 3, 6], [1, 4, 9, 36])

In [ ]:
import pandas as pd
music=pd.read_excel(r'C:\Users\Administrateur\Documents\MEGA\DEV\Python\Data\music2.xlsx')
music

In [ ]:
music.to_csv(r'C:\Users\Administrateur\Documents\MEGA\DEV\Python\Data\music.csv')

In [ ]:
music.head()

In [ ]:
music.info()

In [ ]:
X=music.drop(columns=['music','Unnamed: 0','id'])
X

In [ ]:
Y=music['music']
Y

In [ ]:
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score

model=DecisionTreeClassifier()
model.fit(X,Y)

x_train, x_test, y_train, y_test=train_test_split(X,Y, test_size=0.2)

predictions=model.predict(x_test)
score=accuracy_score(y_test,predictions)
score

In [ ]:
import numpy as np
import matplotlib.pyplot as plt
df = pd.DataFrame(np.random.randn(100, 5), columns=list('ABCDE'))
df=df.cumsum() # Return cumulative sum over a DataFrame or Series axis
df.plot()
plt.show()

In [ ]:
df.describe()

In [ ]:
df.dropna(axis=0)

In [ ]:
df['A'].value_counts()

In [ ]:
df[1:10]['A'].value_counts().plot.bar()

In [ ]:
df.groupby(['A']).mean()

In [ ]:
df[df['A']>12].groupby(['A','C']).mean()

In [ ]:
df.loc[0:2,('A','B')]

In [ ]:
import numpy as np  #NDArray
 
a = np.array([1,1, 3, 6])
b = np.linspace(0, 2, 4)
c = a - b
c

In [ ]:
np.ones((4,4))

In [ ]:
np.full((2,3),7)

In [ ]:
import numpy as np
M = np.zeros(shape=(2, 3))
M

In [ ]:
a = np.linspace(-np.pi, np.pi, 100)
a

In [ ]:
np.linspace(0,1,100)

In [ ]:
#np.random.seed(32425)
np.random.randn(3,5)

In [ ]:
np.random.randint(1,9)

In [ ]:
import numpy as np
import matplotlib.pyplot as plt
Z= np.random.normal(0,1,100)
plt.plot(Z)

In [ ]:
np.arange(1,9,0.5)

In [ ]:
df=pd.DataFrame(np.random.randn(100,5), columns=list('ABCDE'))
df=df.cumsum()
df.plot()

In [ ]:
M=np.zeros(shape=(3,4))
M

In [ ]:
K=np.random.randn(4,4)
K
b=np.linspace(2,7,4)
b
np.linalg.solve(K,b)

In [ ]:
np.linalg.inv(K)

In [ ]:
K.shape
M.shape
np.vstack((K,M))

In [ ]:
np.hstack((M+3,N+2))

In [ ]:
np.concatenate((M,N),axis=0)
np.concatenate((M,N),axis=0)

In [ ]:
N.reshape((2,6))

In [ ]:
A=np.array([1,2,4,3])
A.shape
A=A.reshape(A.shape[0],1)
A.shape

In [ ]:

A=A.squeeze()
A.shape

In [ ]:
A=np.array([['Anne','Peter','Franck','Julia','Cath'],
    [28,32,21,39,35],
    [False,True,True,False,True]])
A

In [ ]:
dfA=pd.DataFrame(A.transpose(),columns=list('ABC'))
dfA

In [ ]:
dfA.drop(['A'],axis=1).groupby(['C']).mean()

CUSTOM DATAFRAMEs

In [68]:
df_prices = pd.DataFrame( columns=['date','open','high','low','close','volume'],dtype=float, index=pd.date_range(start='2023-01-01', periods=100), data= 10+np.random.randn(100,6) )
df_prices['volume'] = 1000
df_prices['date']= df_prices.index
df_prices['id']= np.random.randint(0,10,100)
df_prices

                 date       open       high        low      close  volume  id
2023-01-01 2023-01-01  10.187479   9.699600  10.085920  11.773428    1000   9
2023-01-02 2023-01-02  11.362069  11.066651  10.640214   7.294987    1000   2
2023-01-03 2023-01-03   8.932464   8.968297   8.747819   9.748771    1000   2
2023-01-04 2023-01-04  10.350870   9.175277  10.244785  11.095200    1000   7
2023-01-05 2023-01-05  11.001926  12.588473  10.614408   9.259713    1000   4
...               ...        ...        ...        ...        ...     ...  ..
2023-04-06 2023-04-06  10.622435   9.565674  10.196011   9.660002    1000   3
2023-04-07 2023-04-07  10.251213  10.411077   9.718327  10.057066    1000   2
2023-04-08 2023-04-08   9.433828   7.498865   9.007354   9.890613    1000   3
2023-04-09 2023-04-09   7.753029  11.966746   9.113398   9.660561    1000   8
2023-04-10 2023-04-10  10.873904  10.199590   9.675533   9.011741    1000   9

[100 rows x 7 columns]

In [69]:
df_stocks = pd.DataFrame( columns=['id','name','sector'], data= [[1,'AAPL','Tech'],[2,'MSFT','Tech'],[3,'GOOGL','Tech'],[4,'AMZN','ConsDis'],[5,'TSLA','ConsDis']] )
df_stocks

   id   name   sector
0   1   AAPL     Tech
1   2   MSFT     Tech
2   3  GOOGL     Tech
3   4   AMZN  ConsDis
4   5   TSLA  ConsDis

In [66]:
df_left_merge =   pd.merge(df_prices, df_stocks, on='id', how='left')
df_left_merge

,date,open,high,low,close,volume,id,name,sector
0,2023-01-01,9.212214,10.347263,12.017966,9.311729,1000,7,NaN,NaN
1,2023-01-02,7.532778,11.467009,9.870628,10.175492,1000,4,AMZN,ConsDis
2,2023-01-03,10.423161,10.778593,10.407299,9.825899,1000,6,NaN,NaN
3,2023-01-04,9.123755,10.923663,9.214561,10.559193,1000,7,NaN,NaN
4,2023-01-05,10.606932,9.877530,9.821312,9.993011,1000,3,GOOGL,Tech
...,...,...,...,...,...,...,...,...,...
95,2023-04-06,7.896916,10.493697,10.463439,8.818519,1000,9,NaN,NaN
96,2023-04-07,11.449329,12.724095,10.421240,9.991097,1000,8,NaN,NaN
97,2023-04-08,10.069080,8.842509,9.779720,10.303809,1000,3,GOOGL,Tech
98,2023-04-09,11.160948,9.968258,8.002506,10.766538,1000,9,NaN,NaN
99,2023-04-10,8.532565,9.651654,11.083617,11.259808,1000,9,NaN,NaN

In [70]:
df_right_merge =   pd.merge(df_prices, df_stocks, on='id', how='right')
df_right_merge

,date,open,high,low,close,volume,id,name,sector
0,2023-01-18,10.575450,10.376266,9.332524,9.736023,1000,1,AAPL,Tech
1,2023-01-22,9.676494,12.456273,9.908067,10.412507,1000,1,AAPL,Tech
2,2023-02-04,8.943274,9.809393,9.971544,9.904200,1000,1,AAPL,Tech
3,2023-02-08,10.411413,8.817138,10.511901,11.244041,1000,1,AAPL,Tech
4,2023-02-13,10.103008,9.361170,11.403971,10.947779,1000,1,AAPL,Tech
5,2023-02-26,10.277457,8.647626,7.776981,10.056368,1000,1,AAPL,Tech
6,2023-03-09,10.126453,11.320986,10.605526,9.665356,1000,1,AAPL,Tech
7,2023-03-16,9.187773,9.308584,9.235308,10.875670,1000,1,AAPL,Tech
8,2023-03-29,8.262802,8.857407,10.808654,8.677684,1000,1,AAPL,Tech
9,2023-01-02,11.362069,11.066651,10.640214,7.294987,1000,2,MSFT,Tech
10,2023-01-03,8.932464,8.968297,8.747819,9.748771,1000,2,MSFT,Tech
11,2023-01-24,9.685155,9.526387,9.502330,11.021984,1000,2,MSFT,Tech
12,2023-03-15,9.719147,9.687813,8.573391,9.903099,1000,2,MSFT,Tech
13,2023-03-19,8.285024,8.707769,11.278542,10.168446,1000,2,MSFT,Tech
14,2023-03-22,10.558418,11.248942,10.998893,9.458167,1000,2,MSFT,Tech
15,2023-03-25,10.545721,8.818260,9.721834,8.640954,1000,2,MSFT,Tech
16,2023-03-30,9.600349,10.150673,8.119162,9.494940,1000,2,MSFT,Tech
17,2023-04-03,11.616006,9.107246,10.268015,11.324941,1000,2,MSFT,Tech
18,2023-04-07,10.251213,10.411077,9.718327,10.057066,1000,2,MSFT,Tech
19,2023-01-13,7.945413,8.249912,8.536689,10.371849,1000,3,GOOGL,Tech
20,2023-01-14,8.660142,10.524684,8.195698,8.626511,1000,3,GOOGL,Tech
21,2023-02-17,10.418396,9.732780,10.945778,8.979436,1000,3,GOOGL,Tech
22,2023-02-18,11.691260,10.825323,11.442194,10.425022,1000,3,GOOGL,Tech
23,2023-02-19,10.887668,9.482043,7.331737,10.866712,1000,3,GOOGL,Tech
24,2023-03-04,10.876193,10.998125,8.735128,10.057771,1000,3,GOOGL,Tech
25,2023-03-08,10.275286,9.571345,9.227803,7.657342,1000,3,GOOGL,Tech
26,2023-03-28,8.397411,11.284300,9.347435,10.614460,1000,3,GOOGL,Tech
27,2023-04-01,11.787349,9.712061,10.609909,11.773841,1000,3,GOOGL,Tech
28,2023-04-06,10.622435,9.565674,10.196011,9.660002,1000,3,GOOGL,Tech
29,2023-04-08,9.433828,7.498865,9.007354,9.890613,1000,3,GOOGL,Tech
30,2023-01-05,11.001926,12.588473,10.614408,9.259713,1000,4,AMZN,ConsDis
31,2023-02-06,11.208226,8.471367,9.569653,11.735568,1000,4,AMZN,ConsDis
32,2023-02-09,10.175527,9.376829,10.924981,8.692968,1000,4,AMZN,ConsDis
33,2023-02-15,10.436171,10.069607,10.474765,11.391962,1000,4,AMZN,ConsDis
34,2023-03-01,9.317178,11.102990,9.264755,8.673876,1000,4,AMZN,ConsDis
35,2023-03-11,11.028439,10.460725,11.419351,11.159828,1000,4,AMZN,ConsDis
36,2023-03-23,10.573877,10.414136,8.348626,9.452280,1000,4,AMZN,ConsDis
37,2023-01-11,9.792112,10.355525,9.518342,9.854186,1000,5,TSLA,ConsDis
38,2023-01-21,9.385861,9.519198,9.721154,10.379122,1000,5,TSLA,ConsDis
39,2023-01-23,9.918632,10.500997,12.358789,11.322837,1000,5,TSLA,ConsDis
40,2023-01-25,8.975301,9.288888,9.072871,7.043413,1000,5,TSLA,ConsDis
41,2023-01-28,10.186343,10.420411,10.357257,8.798767,1000,5,TSLA,ConsDis
42,2023-01-30,9.243774,11.476476,9.785691,10.235612,1000,5,TSLA,ConsDis
43,2023-02-20,9.869162,9.405585,11.358259,8.366014,1000,5,TSLA,ConsDis
44,2023-02-23,10.696834,11.901443,11.061047,10.130671,1000,5,TSLA,ConsDis
45,2023-02-24,9.990316,9.633378,9.029036,11.294645,1000,5,TSLA,ConsDis
46,2023-03-12,10.116483,10.211571,10.355988,8.768216,1000,5,TSLA,ConsDis
47,2023-03-24,9.152837,9.041194,10.112256,10.297359,1000,5,TSLA,ConsDis
48,2023-03-27,9.550167,10.081782,11.681066,9.052948,1000,5,TSLA,ConsDis
49,2023-03-31,11.899957,9.822983,9.619100,10.704131,1000,5,TSLA,ConsDis

In [71]:
df_inner_merge =  pd.merge(df_prices, df_stocks, on='id', how='inner')
df_inner_merge

,date,open,high,low,close,volume,id,name,sector
0,2023-01-02,11.362069,11.066651,10.640214,7.294987,1000,2,MSFT,Tech
1,2023-01-03,8.932464,8.968297,8.747819,9.748771,1000,2,MSFT,Tech
2,2023-01-24,9.685155,9.526387,9.502330,11.021984,1000,2,MSFT,Tech
3,2023-03-15,9.719147,9.687813,8.573391,9.903099,1000,2,MSFT,Tech
4,2023-03-19,8.285024,8.707769,11.278542,10.168446,1000,2,MSFT,Tech
5,2023-03-22,10.558418,11.248942,10.998893,9.458167,1000,2,MSFT,Tech
6,2023-03-25,10.545721,8.818260,9.721834,8.640954,1000,2,MSFT,Tech
7,2023-03-30,9.600349,10.150673,8.119162,9.494940,1000,2,MSFT,Tech
8,2023-04-03,11.616006,9.107246,10.268015,11.324941,1000,2,MSFT,Tech
9,2023-04-07,10.251213,10.411077,9.718327,10.057066,1000,2,MSFT,Tech
10,2023-01-05,11.001926,12.588473,10.614408,9.259713,1000,4,AMZN,ConsDis
11,2023-02-06,11.208226,8.471367,9.569653,11.735568,1000,4,AMZN,ConsDis
12,2023-02-09,10.175527,9.376829,10.924981,8.692968,1000,4,AMZN,ConsDis
13,2023-02-15,10.436171,10.069607,10.474765,11.391962,1000,4,AMZN,ConsDis
14,2023-03-01,9.317178,11.102990,9.264755,8.673876,1000,4,AMZN,ConsDis
15,2023-03-11,11.028439,10.460725,11.419351,11.159828,1000,4,AMZN,ConsDis
16,2023-03-23,10.573877,10.414136,8.348626,9.452280,1000,4,AMZN,ConsDis
17,2023-01-11,9.792112,10.355525,9.518342,9.854186,1000,5,TSLA,ConsDis
18,2023-01-21,9.385861,9.519198,9.721154,10.379122,1000,5,TSLA,ConsDis
19,2023-01-23,9.918632,10.500997,12.358789,11.322837,1000,5,TSLA,ConsDis
20,2023-01-25,8.975301,9.288888,9.072871,7.043413,1000,5,TSLA,ConsDis
21,2023-01-28,10.186343,10.420411,10.357257,8.798767,1000,5,TSLA,ConsDis
22,2023-01-30,9.243774,11.476476,9.785691,10.235612,1000,5,TSLA,ConsDis
23,2023-02-20,9.869162,9.405585,11.358259,8.366014,1000,5,TSLA,ConsDis
24,2023-02-23,10.696834,11.901443,11.061047,10.130671,1000,5,TSLA,ConsDis
25,2023-02-24,9.990316,9.633378,9.029036,11.294645,1000,5,TSLA,ConsDis
26,2023-03-12,10.116483,10.211571,10.355988,8.768216,1000,5,TSLA,ConsDis
27,2023-03-24,9.152837,9.041194,10.112256,10.297359,1000,5,TSLA,ConsDis
28,2023-03-27,9.550167,10.081782,11.681066,9.052948,1000,5,TSLA,ConsDis
29,2023-03-31,11.899957,9.822983,9.619100,10.704131,1000,5,TSLA,ConsDis
30,2023-01-13,7.945413,8.249912,8.536689,10.371849,1000,3,GOOGL,Tech
31,2023-01-14,8.660142,10.524684,8.195698,8.626511,1000,3,GOOGL,Tech
32,2023-02-17,10.418396,9.732780,10.945778,8.979436,1000,3,GOOGL,Tech
33,2023-02-18,11.691260,10.825323,11.442194,10.425022,1000,3,GOOGL,Tech
34,2023-02-19,10.887668,9.482043,7.331737,10.866712,1000,3,GOOGL,Tech
35,2023-03-04,10.876193,10.998125,8.735128,10.057771,1000,3,GOOGL,Tech
36,2023-03-08,10.275286,9.571345,9.227803,7.657342,1000,3,GOOGL,Tech
37,2023-03-28,8.397411,11.284300,9.347435,10.614460,1000,3,GOOGL,Tech
38,2023-04-01,11.787349,9.712061,10.609909,11.773841,1000,3,GOOGL,Tech
39,2023-04-06,10.622435,9.565674,10.196011,9.660002,1000,3,GOOGL,Tech
40,2023-04-08,9.433828,7.498865,9.007354,9.890613,1000,3,GOOGL,Tech
41,2023-01-18,10.575450,10.376266,9.332524,9.736023,1000,1,AAPL,Tech
42,2023-01-22,9.676494,12.456273,9.908067,10.412507,1000,1,AAPL,Tech
43,2023-02-04,8.943274,9.809393,9.971544,9.904200,1000,1,AAPL,Tech
44,2023-02-08,10.411413,8.817138,10.511901,11.244041,1000,1,AAPL,Tech
45,2023-02-13,10.103008,9.361170,11.403971,10.947779,1000,1,AAPL,Tech
46,2023-02-26,10.277457,8.647626,7.776981,10.056368,1000,1,AAPL,Tech
47,2023-03-09,10.126453,11.320986,10.605526,9.665356,1000,1,AAPL,Tech
48,2023-03-16,9.187773,9.308584,9.235308,10.875670,1000,1,AAPL,Tech
49,2023-03-29,8.262802,8.857407,10.808654,8.677684,1000,1,AAPL,Tech

In [72]:
df_inner_merge['sumOfVolume'] = df_inner_merge.groupby(['id'])['volume'].sum()
df_inner_merge

,date,open,high,low,close,volume,id,name,sector,sumOfVolume
0,2023-01-02,11.362069,11.066651,10.640214,7.294987,1000,2,MSFT,Tech,NaN
1,2023-01-03,8.932464,8.968297,8.747819,9.748771,1000,2,MSFT,Tech,9000.0
2,2023-01-24,9.685155,9.526387,9.502330,11.021984,1000,2,MSFT,Tech,10000.0
3,2023-03-15,9.719147,9.687813,8.573391,9.903099,1000,2,MSFT,Tech,11000.0
4,2023-03-19,8.285024,8.707769,11.278542,10.168446,1000,2,MSFT,Tech,7000.0
5,2023-03-22,10.558418,11.248942,10.998893,9.458167,1000,2,MSFT,Tech,13000.0
6,2023-03-25,10.545721,8.818260,9.721834,8.640954,1000,2,MSFT,Tech,NaN
7,2023-03-30,9.600349,10.150673,8.119162,9.494940,1000,2,MSFT,Tech,NaN
8,2023-04-03,11.616006,9.107246,10.268015,11.324941,1000,2,MSFT,Tech,NaN
9,2023-04-07,10.251213,10.411077,9.718327,10.057066,1000,2,MSFT,Tech,NaN
10,2023-01-05,11.001926,12.588473,10.614408,9.259713,1000,4,AMZN,ConsDis,NaN
11,2023-02-06,11.208226,8.471367,9.569653,11.735568,1000,4,AMZN,ConsDis,NaN
12,2023-02-09,10.175527,9.376829,10.924981,8.692968,1000,4,AMZN,ConsDis,NaN
13,2023-02-15,10.436171,10.069607,10.474765,11.391962,1000,4,AMZN,ConsDis,NaN
14,2023-03-01,9.317178,11.102990,9.264755,8.673876,1000,4,AMZN,ConsDis,NaN
15,2023-03-11,11.028439,10.460725,11.419351,11.159828,1000,4,AMZN,ConsDis,NaN
16,2023-03-23,10.573877,10.414136,8.348626,9.452280,1000,4,AMZN,ConsDis,NaN
17,2023-01-11,9.792112,10.355525,9.518342,9.854186,1000,5,TSLA,ConsDis,NaN
18,2023-01-21,9.385861,9.519198,9.721154,10.379122,1000,5,TSLA,ConsDis,NaN
19,2023-01-23,9.918632,10.500997,12.358789,11.322837,1000,5,TSLA,ConsDis,NaN
20,2023-01-25,8.975301,9.288888,9.072871,7.043413,1000,5,TSLA,ConsDis,NaN
21,2023-01-28,10.186343,10.420411,10.357257,8.798767,1000,5,TSLA,ConsDis,NaN
22,2023-01-30,9.243774,11.476476,9.785691,10.235612,1000,5,TSLA,ConsDis,NaN
23,2023-02-20,9.869162,9.405585,11.358259,8.366014,1000,5,TSLA,ConsDis,NaN
24,2023-02-23,10.696834,11.901443,11.061047,10.130671,1000,5,TSLA,ConsDis,NaN
25,2023-02-24,9.990316,9.633378,9.029036,11.294645,1000,5,TSLA,ConsDis,NaN
26,2023-03-12,10.116483,10.211571,10.355988,8.768216,1000,5,TSLA,ConsDis,NaN
27,2023-03-24,9.152837,9.041194,10.112256,10.297359,1000,5,TSLA,ConsDis,NaN
28,2023-03-27,9.550167,10.081782,11.681066,9.052948,1000,5,TSLA,ConsDis,NaN
29,2023-03-31,11.899957,9.822983,9.619100,10.704131,1000,5,TSLA,ConsDis,NaN
30,2023-01-13,7.945413,8.249912,8.536689,10.371849,1000,3,GOOGL,Tech,NaN
31,2023-01-14,8.660142,10.524684,8.195698,8.626511,1000,3,GOOGL,Tech,NaN
32,2023-02-17,10.418396,9.732780,10.945778,8.979436,1000,3,GOOGL,Tech,NaN
33,2023-02-18,11.691260,10.825323,11.442194,10.425022,1000,3,GOOGL,Tech,NaN
34,2023-02-19,10.887668,9.482043,7.331737,10.866712,1000,3,GOOGL,Tech,NaN
35,2023-03-04,10.876193,10.998125,8.735128,10.057771,1000,3,GOOGL,Tech,NaN
36,2023-03-08,10.275286,9.571345,9.227803,7.657342,1000,3,GOOGL,Tech,NaN
37,2023-03-28,8.397411,11.284300,9.347435,10.614460,1000,3,GOOGL,Tech,NaN
38,2023-04-01,11.787349,9.712061,10.609909,11.773841,1000,3,GOOGL,Tech,NaN
39,2023-04-06,10.622435,9.565674,10.196011,9.660002,1000,3,GOOGL,Tech,NaN
40,2023-04-08,9.433828,7.498865,9.007354,9.890613,1000,3,GOOGL,Tech,NaN
41,2023-01-18,10.575450,10.376266,9.332524,9.736023,1000,1,AAPL,Tech,NaN
42,2023-01-22,9.676494,12.456273,9.908067,10.412507,1000,1,AAPL,Tech,NaN
43,2023-02-04,8.943274,9.809393,9.971544,9.904200,1000,1,AAPL,Tech,NaN
44,2023-02-08,10.411413,8.817138,10.511901,11.244041,1000,1,AAPL,Tech,NaN
45,2023-02-13,10.103008,9.361170,11.403971,10.947779,1000,1,AAPL,Tech,NaN
46,2023-02-26,10.277457,8.647626,7.776981,10.056368,1000,1,AAPL,Tech,NaN
47,2023-03-09,10.126453,11.320986,10.605526,9.665356,1000,1,AAPL,Tech,NaN
48,2023-03-16,9.187773,9.308584,9.235308,10.875670,1000,1,AAPL,Tech,NaN
49,2023-03-29,8.262802,8.857407,10.808654,8.677684,1000,1,AAPL,Tech,NaN

In [82]:
employees = pd.DataFrame({'first_name':['John','Jane','Mary','Peter','Paul']*2,
                         'last_name':['Doe','Smith','Johnson','Brown','Davis']*2,
                         'qty':[1,2,3,4,5,1,2,3,4,5],
                         'purchases_id':[5,7,8,6,9,1,5,7,6,8]})
employees

  first_name last_name  qty  purchases_id
0       John       Doe    1             5
1       Jane     Smith    2             7
2       Mary   Johnson    3             8
3      Peter     Brown    4             6
4       Paul     Davis    5             9
5       John       Doe    1             1
6       Jane     Smith    2             5
7       Mary   Johnson    3             7
8      Peter     Brown    4             6
9       Paul     Davis    5             8

In [83]:
products = pd.DataFrame({'product_id':[1, 5,6,7,8,9], 'price':[20, 100,150,200,250,300]})
products

   product_id  price
0           1     20
1           5    100
2           6    150
3           7    200
4           8    250
5           9    300

In [ ]:
costs = pd.merge(employees, products, left_on='purchases_id', right_on='product_id', how='left')
costs

  first_name last_name  qty  purchases_id  product_id  price
0       John       Doe    1             5           5    100
1       Jane     Smith    2             7           7    200
2       Mary   Johnson    3             8           8    250
3      Peter     Brown    4             6           6    150
4       Paul     Davis    5             9           9    300
5       John       Doe    1             1           1     20
6       Jane     Smith    2             5           5    100
7       Mary   Johnson    3             7           7    200
8      Peter     Brown    4             6           6    150
9       Paul     Davis    5             8           8    250

In [86]:
costs['total_cost'] = costs['price'] * costs['qty']
costs

  first_name last_name  qty  purchases_id  product_id  price  total_cost
0       John       Doe    1             5           5    100         100
1       Jane     Smith    2             7           7    200         400
2       Mary   Johnson    3             8           8    250         750
3      Peter     Brown    4             6           6    150         600
4       Paul     Davis    5             9           9    300        1500
5       John       Doe    1             1           1     20          20
6       Jane     Smith    2             5           5    100         200
7       Mary   Johnson    3             7           7    200         600
8      Peter     Brown    4             6           6    150         600
9       Paul     Davis    5             8           8    250        1250

In [88]:
costs_per_person = costs.groupby(['first_name','last_name'])['total_cost'].sum().reset_index()
costs_per_person

  first_name last_name  total_cost
0       Jane     Smith         600
1       John       Doe         120
2       Mary   Johnson        1350
3       Paul     Davis        2750
4      Peter     Brown        1200

In [102]:
def my_custom_adjustment(x)-> float:
    return x *0.977


costs_per_person['total_cost'].transform(my_custom_adjustment)
costs_per_person

  first_name last_name  total_cost
0       Jane     Smith         600
1       John       Doe         120
2       Mary   Johnson        1350
3       Paul     Davis        2750
4      Peter     Brown        1200

astype - memory_usage

In [103]:
# Large DataFrame with repetitive strings
df = pd.DataFrame({
    'category': ['A', 'B', 'A', 'C'] * 1000000,
    'value': np.random.randn(4000000)
})

# Before optimization
print(df.memory_usage(deep=True).sum() / 1024**2, 'MB')  # ~240 MB

# Convert to category
df['category'] = df['category'].astype('category')
print(df.memory_usage(deep=True).sum() / 1024**2, 'MB')  # ~30 MB

251.7701416015625 MB
34.33266639709473 MB

In [105]:
dates = pd.date_range('2025-01-01', '2025-12-31', freq='D')
dates

DatetimeIndex(['2025-01-01', '2025-01-02', '2025-01-03', '2025-01-04',
               '2025-01-05', '2025-01-06', '2025-01-07', '2025-01-08',
               '2025-01-09', '2025-01-10',
               ...
               '2025-12-22', '2025-12-23', '2025-12-24', '2025-12-25',
               '2025-12-26', '2025-12-27', '2025-12-28', '2025-12-29',
               '2025-12-30', '2025-12-31'],
              dtype='datetime64[ns]', length=365, freq='D')

In [106]:
df = pd.DataFrame({'value': np.random.randn(len(dates))}, index=dates)
df

               value
2025-01-01 -1.453868
2025-01-02 -0.744833
2025-01-03  0.283440
2025-01-04  0.250335
2025-01-05 -0.663979
...              ...
2025-12-27  1.386027
2025-12-28  0.932806
2025-12-29 -1.161051
2025-12-30 -2.232525
2025-12-31  1.502162

[365 rows x 1 columns]

In [110]:
monthly_avg = df.resample('2M').mean()
monthly_avg

               value
2025-01-31 -0.297252
2025-03-31  0.140268
2025-05-31 -0.102289
2025-07-31  0.051400
2025-09-30 -0.143899
2025-11-30 -0.029688
2026-01-31 -0.144586

MISSING DATA

In [112]:
df = pd.DataFrame({
    'name': ['Alice', 'Bob', None, 'David'],
    'age': [25, None, 30, 35],
    'score': [85, 90, np.nan, 95]
})
df

    name   age  score
0  Alice  25.0   85.0
1    Bob   NaN   90.0
2   None  30.0    NaN
3  David  35.0   95.0

In [113]:
# Fill missing values
df['name'] = df['name'].fillna('Unknown')
df['age'] = df['age'].fillna(df['age'].mean())
df['score'] = df['score'].interpolate()
df

      name   age  score
0    Alice  25.0   85.0
1      Bob  30.0   90.0
2  Unknown  30.0   92.5
3    David  35.0   95.0

In [116]:
sales_data = pd.DataFrame({
    'date': pd.date_range('2025-01-01', periods=1000, freq='D'),
    'product': np.random.choice(['Laptop', 'Phone', 'Tablet'], 1000),
    'region': np.random.choice(['North', 'South', 'East', 'West'], 1000),
    'sales': np.random.randint(100, 1000, 1000),
    'discount': np.random.uniform(0, 0.3, 1000)
})

sales_data

          date product region  sales  discount
0   2025-01-01   Phone  South    914  0.268795
1   2025-01-02  Laptop  South    417  0.263541
2   2025-01-03  Tablet  South    130  0.081490
3   2025-01-04  Laptop   East    854  0.050929
4   2025-01-05  Laptop  South    444  0.268333
..         ...     ...    ...    ...       ...
995 2027-09-23  Tablet  North    225  0.164833
996 2027-09-24  Laptop  South    825  0.196656
997 2027-09-25   Phone  South    413  0.125093
998 2027-09-26   Phone   West    949  0.254307
999 2027-09-27  Tablet  North    567  0.297128

[1000 rows x 5 columns]

In [118]:
sales_data.loc[np.random.choice(sales_data.index, 50), 'sales'] = np.nan
sales_data

          date product region  sales  discount
0   2025-01-01   Phone  South  914.0  0.268795
1   2025-01-02  Laptop  South  417.0  0.263541
2   2025-01-03  Tablet  South  130.0  0.081490
3   2025-01-04  Laptop   East  854.0  0.050929
4   2025-01-05  Laptop  South  444.0  0.268333
..         ...     ...    ...    ...       ...
995 2027-09-23  Tablet  North  225.0  0.164833
996 2027-09-24  Laptop  South  825.0  0.196656
997 2027-09-25   Phone  South  413.0  0.125093
998 2027-09-26   Phone   West  949.0  0.254307
999 2027-09-27  Tablet  North  567.0  0.297128

[1000 rows x 5 columns]

In [120]:
sales_data['sales'] = sales_data.groupby(['product','region'])['sales'].transform(lambda x: x.fillna(x.median()))
sales_data

          date product region  sales  discount
0   2025-01-01   Phone  South  914.0  0.268795
1   2025-01-02  Laptop  South  417.0  0.263541
2   2025-01-03  Tablet  South  130.0  0.081490
3   2025-01-04  Laptop   East  854.0  0.050929
4   2025-01-05  Laptop  South  444.0  0.268333
..         ...     ...    ...    ...       ...
995 2027-09-23  Tablet  North  225.0  0.164833
996 2027-09-24  Laptop  South  825.0  0.196656
997 2027-09-25   Phone  South  413.0  0.125093
998 2027-09-26   Phone   West  949.0  0.254307
999 2027-09-27  Tablet  North  567.0  0.297128

[1000 rows x 5 columns]

In [122]:
total_sales = sales_data.groupby(['product', 'region'])['sales'].apply(sum).reset_index()
total_sales

   product region    sales
0   Laptop   East  48225.0
1   Laptop  North  50901.0
2   Laptop  South  58511.0
3   Laptop   West  40228.0
4    Phone   East  49908.0
5    Phone  North  44022.0
6    Phone  South  53983.0
7    Phone   West  41825.0
8   Tablet   East  41763.0
9   Tablet  North  38411.0
10  Tablet  South  46494.0
11  Tablet   West  35106.0